# -*- coding: utf-8 -*-
"""label_formatter

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SbcQDCO13Hc7J73ebFasGMTdW23tf4CR
"""

import os

clothes_dataset_path = r"C:\Users\admin\Desktop\clothes_dataset"

like_new_path= os.path.join(clothes_dataset_path,"0_LikeNew")
slightly_worn_path=os.path.join(clothes_dataset_path,"1_SlightlyWorn")
heavily_worn_path=os.path.join(clothes_dataset_path,"2_HeavilyWorn")

for folder, label in [(like_new_path,0),(slightly_worn_path,1),(heavily_worn_path,2)]:
    if os.path.exists(folder):
        for filename in os.listdir(folder):
            if filename.lower().endswith((".jpg",".jpeg",".png",".pdf")):
                old_path=os.path.join(folder,filename)
                name, ext = os.path.splitext(filename)
                new_name= f"{name}_{label}{ext}"
                newpath = os.path.join(folder,new_name)

                os.rename(old_path, newpath)

        print(f"Folder {folder} renamed to {newpath}")

print("Done")